### ISSUE TITLE
Build issues on macOS

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#217]
```
In file included from ../src/modules/cairo/cairo.cc:13:
In file included from ../src/modules/cairo/font-face.h:15:
In file included from /usr/local/Cellar/cairo/1.16.0_3/include/cairo/cairo-quartz.h:43:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:77:
/usr/include/MacTypes.h:309:41: error: typedef redefinition with different types ('unsigned char' vs 'v8::Boolean')
typedef unsigned char                   Boolean;
```

https://travis-ci.org/github/romgrk/node-gtk/jobs/736552109#L6350-L6358
https://gitlab.freedesktop.org/cairo/cairo/-/issues/429

**Comment by romgrk** [comment]
Observations:
 - Comparing the build for v0.4.0 (6 months ago) and v0.5.0 (today) shows that the version of cairo stayed constant (`cairo-1.16.0_3`)
 - I've relaunched the v0.4.0 build today, and it failed, but the build from 6 months ago passed! This means that the issue is probably not with Cairo but with the environment. Makes sense because the conflicting identifier comes from what seems like a macOS system header.

**Comment by WebReflection** [comment]
I've tried to change, remove, the `typedef unsigned char Boolean` in macOS header without success, but if cairo version was the same before I don't understand why it fails now ... I've tried both node 14 and 15, maybe I should try node 12 instead?

**Comment by wotzlaff** [comment]
The name `Boolean` is used in the present version of the macOS system and framework headers. (To be honest I am not sure whether this statement is fully correct because I am no macOS user.)
This causes a conflict if we use `using v8::Boolean;`. I gave a quick fix in #230, but maybe we should be more careful with the other `using` statements, too.

**Comment by WebReflection** [comment]
I can confirm your branch works on macOS Catalina 10.15.7 too
