### PR TITLE
Remove using v8::Boolean

### LINKED ISSUE #217: Build issues on macOS
```
In file included from ../src/modules/cairo/cairo.cc:13:
In file included from ../src/modules/cairo/font-face.h:15:
In file included from /usr/local/Cellar/cairo/1.16.0_3/include/cairo/cairo-quartz.h:43:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:77:
/usr/include/MacTypes.h:309:41: error: typedef redefinition with different types ('unsigned char' vs 'v8::Boolean')
typedef unsigned char                   Boolean;
```

https://travis-ci.org/github/romgrk/node-gtk/jobs/736552109#L6350-L6358
https://gitlab.freedesktop.org/cairo/cairo/-/issues/429

### PR DESCRIPTION
**Pull request by wotzlaff**
We were having issue building on macOS because the name `Boolean` was exposed by `using v8::Boolean;`.
I fixed it by using `v8::Boolean` explicitly at the corresponding places.
Now it compiles successfully on the recent beta of Big Sur.

I am still waiting for the tests to pass.

Fixes #217

### CODE REVIEW

**Comment by WebReflection** [comment]
I can confirm your branch works on macOS Catalina 10.15.7 too

**Comment by WebReflection** [comment]
5 errors though


  44 passing (45s)
  5 failing

  1) callback.js:
     Failed: callback run from another thread spawned from GstPipeline
Could not create all elements.
[WARN] gi.cc: GetConstantValue: 139: Couldn't load Gst.BUFFER_COPY_ALL: invalid constant size: 0
[WARN] gi.cc: GetConstantValue: 139: Couldn't load Gst.BUFFER_COPY_METADATA: invalid constant size: 0
[WARN] gi.cc: GetConstantValue: 139: Couldn't load Gst.EVENT_TYPE_BOTH: invalid constant size: 0
[WARN] gi.cc: GetConstantValue: 139: Couldn't load Gst.LOCK_FLAG_READWRITE: invalid constant size: 0
[WARN] gi.cc: GetConstantValue: 139: Couldn't load Gst.MAP_READWRITE: invalid constant size: 0
[WARN] gi.cc: GetConstantValue: 139: Couldn't load Gst.QUERY_TYPE_BOTH: invalid constant size: 0
Run loop.
count 0
count 1
count 2
count 3
Loop ran.
Success: callback value is set
Success: callback run from another thread spawned from GTask
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

  

  2) conversion__array.js:
     Failed: undefined
[WARN] gi.cc: GetConstantValue: 139: Couldn't load HarfBuzz.LANGUAGE_INVALID: invalid constant size: 0
Result: aGVsbG8=
Result: 5d41402abc4b2a76b9719d911017c592
Result: [
  true,
  [
     47,  42,  10,  32,  42,  32,  99, 111, 110, 118, 101, 114,
    115, 105, 111, 110,  95,  95,  97, 114, 114,  97, 121,  46,
    106, 115,  10,  32,  42,  47,  10,  10,  10,  99, 111, 110,
    115, 116,  32, 102, 115,  32,  61,  32, 114, 101, 113, 117,
    105, 114, 101,  40,  39, 102, 115,  39,  41,  10,  99, 111,
    110, 115, 116,  32, 112,  97, 116, 104,  32,  61,  32, 114,
    101, 113, 117, 105, 114, 101,  40,  39, 112,  97, 116, 104,
     39,  41,  10,  99, 111, 110, 115, 116,  32, 103, 105,  32,
     61,  32, 114, 101,
    ... 1340 more items
  ]
]
Result: [ 'argument1', '--gtk-debug', 'misc', 'argument2' ]
    at Object.<anonymous> (/Users/webreflection/git/node-gtk/tests/conversion__array.js:55:10)

  

  3) function_call__inout.js:
     [ 'argument1', '--gtk-debug', 'misc', 'argument2' ] expected length === 2
[WARN] gi.cc: GetConstantValue: 139: Couldn't load HarfBuzz.LANGUAGE_INVALID: invalid constant size: 0

  

  4) cairo/font-face.js:
     Failed: FontFace: .status(), .getType(), .getReferenceCount(): Expected: "0", got: "8"
    at /Users/webreflection/git/node-gtk/tests/cairo/font-face.js:17:5

  

  5) cairo/scaled-font.js:
     Failed: ScaledFont: .textToGlyphs(): Expected: "5", got: "0"
Success: ScaledFont: .create(...)
    at /Users/webreflection/git/node-gtk/tests/cairo/scaled-font.js:26:5

**Comment by wotzlaff** [comment]
I can confirm these errors. Errors 1-3 are also present on travis.
I will try to find out what's wrong there. But at least the build problems should be fixed now.

**Comment by wotzlaff** [comment]
We can break it down into three issues:
- a problem in `callback.js`: `webrtcbin` is missing for some reason
- a problem with `Gtk.init`: the out params are not set correctly (everything which goes in comes out, but two elements should be stripped away?)
- a problem with cairo in loading fonts: `font.status()` from `const font = Cairo.FontFace.create('Arial', Cairo.FontSlant.OBLIQUE, Cairo.FontWeight.BOLD)` is `Cairo.Status.INVALID_STRING` instead of `Cairo.Status.SUCCESS`. This issue is not present in travis.

**Comment by WebReflection** [comment]
I think I don't have Arial font installed though, but I'm not sure that's part of the issue.

**Comment by romgrk** [comment]
Awesome! I was minded to debug the underlying build/linking issue but tbh this is way better. Might also be the only way to solve it.

If this PR solves the compilation problems, I'll merge it as it is, and let's open issues separate issues for each failing test. We can group font test 4 & 5 together I think.

**Comment by wotzlaff** [comment]
I added three new issues with a short summary.

**Comment by romgrk** [comment]
LGTM. And Travis is back with us.
