### ISSUE TITLE
Unable to build on node 10.7.0

### ISSUE THREAD

**Issue by romgrk** [romgrk/node-gtk#86]
Probably a Nan issue.

```
$ npm install node-gtk
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)

> node-gtk@0.2.0 install /Users/me/node_modules/node-gtk
> if [ "$(uname)" = "Darwin" ] && [ "$(which brew)" != "" ]; then export PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig; fi; node-pre-gyp install --fallback-to-build

...
  CXX(target) Release/obj.target/node_gtk/src/boxed.o
In file included from ../src/boxed.cc:5:
In file included from ../src/boxed.h:4:
../../nan/nan.h:1081:96: error: too many arguments to function call, expected at most 4, have 5
        length_ = string->WriteUtf8(v8::Isolate::GetCurrent(), str_, static_cast<int>(len), 0, flags);
                  ~~~~~~~~~~~~~~~~~                                                            ^~~~~
/Users/me/.node-gyp/10.7.0/include/node/v8.h:2622:3: note: 'WriteUtf8' declared here
  int WriteUtf8(char* buffer,
  ^
1 error generated.
make: *** [Release/obj.target/node_gtk/src/boxed.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
...
```

**Comment by romgrk** [comment]
Update when https://github.com/nodejs/nan/pull/833 is published.

**Comment by romgrk** [comment]
Pinned to `nan@2.11.1` in 6a8da428390f094bd2bd240bca82f970c88eed00 and published patch version to npm.
